return {
    diagnostics = {
        Error = " ",
        Warning = " ",
        Info = " ",
        Hint = "󰌶 ",
    },
    gitsigns = {
        Add    = "│", --"▎",
        Delete = "",
    },
    debug = {
        Breakpoint          = " ",
        BreakpointCondition = " ",
        BreakpointRejected  = " ",
        Logpoint            = " ",
        Stopped             = " ",
    },
    navic = {
        File          = "󰈙 ",
        Module        = " ",
        Namespace     = "󰌗 ",
        Package       = " ",
        Class         = "󰌗 ",
        Method        = "󰆧 ",
        Property      = " ",
        Field         = " ",
        Constructor   = " ",
        Enum          = "󰕘",
        Interface     = "󰕘",
        Function      = "󰊕 ",
        Variable      = "󰆧 ",
        Constant      = "󰏿 ",
        String        = "󰀬 ",
        Number        = "󰎠 ",
        Boolean       = "◩ ",
        Array         = "󰅪 ",
        Object        = "󰅩 ",
        Key           = "󰌋 ",
        Null          = "󰟢 ",
        EnumMember    = " ",
        Struct        = "󰌗 ",
        Event         = " ",
        Operator      = "󰆕 ",
        TypeParameter = "󰊄 ",
    },
    alpha = {
        Find          = "  ",
        NewFile       = "  ",
        FindProject   = "  ",
        RecentlyUsed  = "  ",
        FindText      = "  ",
        Configuration = "  ",
        Quit          = "  ",
        Session       = "  ",
    },
    bufferline = {
        CloseBuffer = "󰅖",
        Modified    = "●",
        Close       = "",
        LeftMarker  = "",
        RightMarker = "",
        Indicator   = "▎",
    }
}
